services:
  db:
    image: postgres:15-alpine
    container_name: donamed-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: donamed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DONAMED-DB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
